.Dd January 1, 2025
.Dt nanoid 3
.Sh NAME
.Nm nanoid
.Nd generate a Nano ID
.Sh SYNOPSIS
.In nanoid.h
.Ft "int"
.Fn nanoidgen "char *buffer" "size_t length"
.Sh DESCRIPTION
.Dv NANOIDLEN
expands to the default Nano ID length of 21.

.Fn nanoidgen
fills the buffer with a Nano ID of the specified length up to
.Dv GETENTROPY_MAX
(256) and returns the return value of
.Xr getentropy 3 .
.Sh RETURN VALUES
.Rv -std
.Sh SEE ALSO
.Xr nanoidgen 1
.Sh AUTHORS
.An Luka Teras Aq Mt luka@sdf.org
