.Dd December 8, 2024
.Dt nanoidgen 1
.Sh NAME
.Nm nanoidgen
.Nd generate a Nano ID
.Sh SYNOPSIS
.Nm
.Op length
.Sh DESCRIPTION
.Nm
generates a Nano ID of the given length ≤256, or if not given, the default length 21.
.Sh EXIT STATUS
.Ex -std

In particular, 64 signifies a usage error.
.Sh SEE ALSO
.Xr nanoid 3
.Sh AUTHORS
.An Luka Teras Aq Mt luka@sdf.org
