name: Pages

on:
  push:
    branches:
    - trunk

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  man:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt install -y mandoc
    - uses: actions/checkout@v4
    - run: make all
    - uses: actions/upload-pages-artifact@v3
      with:
        path: pub
    - id: deployment
      uses: actions/deploy-pages@v4
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
