name: Pages

on:
  push:
    branches:
    - trunk

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  man:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt install -y mandoc
    - uses: actions/checkout@v4
    - run: mkdir -p pub/man/
    - run: mman -T html ./nanoid.3 > pub/man/nanoid.3.html
    - run: mman -T html ./nanoidgen.1 > pub/man/nanoidgen.1.html
    - run: mman -T pdf ./nanoid.3 ./nanoidgen.1 > pub/man.pdf
    - run: mkdir -p pub/openbsd/man/
    - run: mman -T html ./openbsd/nanoid.3 > pub/openbsd/man/nanoid.3.html
    - run: mman -T pdf ./openbsd/nanoid.3 ./nanoidgen.1 > pub/openbsd/man.pdf
    - uses: actions/upload-pages-artifact@v3
      with:
        path: pub
    - id: deployment
      uses: actions/deploy-pages@v4
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
